# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_GD <- function(X, Y, design, eta = 0.1, etaDrop = 0L, penalty = 0L, lambdaBias = 0.0, lambdaWeight = 0.0, nEpoch = 1000L, epsDeriv = 0, trace = 0L) {
    .Call(`_nnExplorer_rcpp_GD`, X, Y, design, eta, etaDrop, penalty, lambdaBias, lambdaWeight, nEpoch, epsDeriv, trace)
}

rcpp_GDV <- function(X, Y, design, XV, YV, eta = 0.1, etaDrop = 0L, penalty = 0L, lambdaBias = 0.0, lambdaWeight = 0.0, nEpoch = 1000L, epsDeriv = 0.0, maxvrise = 0L, validGap = 1L, trace = 0L) {
    .Call(`_nnExplorer_rcpp_GDV`, X, Y, design, XV, YV, eta, etaDrop, penalty, lambdaBias, lambdaWeight, nEpoch, epsDeriv, maxvrise, validGap, trace)
}

rcpp_SGD <- function(X, Y, design, eta = 0.1, etaDrop = 0L, penalty = 0L, lambdaBias = 0.0, lambdaWeight = 0.0, batch = 20L, nIter = 10L, momentum = 0.0, rmsprop = 0.0, beta = 0.99, warmup = 500L, nEpoch = 1000L, epsDeriv = 0, trace = 0L) {
    .Call(`_nnExplorer_rcpp_SGD`, X, Y, design, eta, etaDrop, penalty, lambdaBias, lambdaWeight, batch, nIter, momentum, rmsprop, beta, warmup, nEpoch, epsDeriv, trace)
}

rcpp_SGDV <- function(X, Y, design, XV, YV, eta = 0.1, etaDrop = 0L, penalty = 0L, lambdaBias = 0.0, lambdaWeight = 0.0, batch = 20L, nIter = 10L, momentum = 0.0, rmsprop = 0.0, beta = 0.99, warmup = 500L, nEpoch = 1000L, epsDeriv = 0, validGap = 1L, trace = 0L) {
    .Call(`_nnExplorer_rcpp_SGDV`, X, Y, design, XV, YV, eta, etaDrop, penalty, lambdaBias, lambdaWeight, batch, nIter, momentum, rmsprop, beta, warmup, nEpoch, epsDeriv, validGap, trace)
}

rcpp_backpropagation <- function(y, v, bias, weight, from, to, nPtr, wPtr, actFun, lossFun) {
    .Call(`_nnExplorer_rcpp_backpropagation`, y, v, bias, weight, from, to, nPtr, wPtr, actFun, lossFun)
}

rcpp_forward_pass <- function(v, bias, weight, from, to, nPtr, wPtr, actFun) {
    .Call(`_nnExplorer_rcpp_forward_pass`, v, bias, weight, from, to, nPtr, wPtr, actFun)
}

rcpp_hello_world <- function() {
    .Call(`_nnExplorer_rcpp_hello_world`)
}

rcpp_predict <- function(X, design) {
    .Call(`_nnExplorer_rcpp_predict`, X, design)
}

rcpp_values <- function(X, design) {
    .Call(`_nnExplorer_rcpp_values`, X, design)
}

